/// Represents a loaded Native Ad from AdMob with all available metadata.
class FlutterNativeAd {
  /// Unique identifier generated by the plugin for this specific ad instance.
  final String id;

  /// The headline of the ad (e.g., "Install App").
  final String? headline;

  /// The main descriptive text of the ad.
  final String? body;

  /// The name of the advertiser (e.g., "Google" or the app developer name).
  final String? advertiser;

  /// URL string for the small square icon image.
  final String? icon;

  /// A list of URLs for large images associated with the ad.
  final List<String> images;

  /// Backward-compatible getter that returns the first image from [images].
  String? get cover => images.isNotEmpty ? images.first : null;

  /// The text for the call-to-action button (e.g., "Install", "Open", "Learn More").
  final String? cta;

  /// The star rating of the advertised product (0.0 to 5.0).
  final double? starRating;

  /// The store name where the app is available (e.g., "Google Play", "App Store").
  final String? store;

  /// The price of the advertised product (e.g., "Free" or "$0.99").
  final String? price;

  /// The URL for the "Why this ad?" (AdChoices) information page.
  final String? adChoicesUrl;

  /// The text to accompany the AdChoices icon (if provided by the SDK).
  final String? adChoicesText;

  FlutterNativeAd({
    required this.id,
    this.headline,
    this.body,
    this.advertiser,
    this.icon,
    this.images = const [],
    this.cta,
    this.starRating,
    this.store,
    this.price,
    this.adChoicesUrl,
    this.adChoicesText,
  });

  /// Creates a [FlutterNativeAd] instance from a [map] received from the native platform.
  factory FlutterNativeAd.fromMap(Map<String, dynamic> map) {
    // Parse images from comma-separated string
    final imagesRaw = map['images'] as String? ?? "";
    final imagesList = imagesRaw.isNotEmpty ? imagesRaw.split(',') : <String>[];

    // Add cover if not already in images
    final cover = map['cover'] as String?;
    if (cover != null && cover.isNotEmpty && !imagesList.contains(cover)) {
      imagesList.insert(0, cover);
    }

    return FlutterNativeAd(
      id: map['id'] as String,
      headline: map['headline'] as String?,
      body: map['body'] as String?,
      advertiser: map['advertiser'] as String?,
      icon: map['icon'] as String?,
      images: imagesList,
      cta: map['cta'] as String?,
      starRating: double.tryParse(map['starRating'] as String? ?? ""),
      store: map['store'] as String?,
      price: map['price'] as String?,
      adChoicesUrl: map['adChoicesUrl'] as String?,
      adChoicesText: map['adChoicesText'] as String?,
    );
  }
}

/// Options for loading one or more native ads.
class FlutterNativeAdOptions {
  /// The AdMob ad unit ID to load.
  final String adId;

  /// Whether to use test ads instead of live ads.
  final bool isTesting;

  /// The number of ads to request from the server (min 1, max 5).
  final int adsCount;

  /// Creates a new [FlutterNativeAdOptions] instance.
  FlutterNativeAdOptions({required this.adId, this.isTesting = false, this.adsCount = 1})
    : assert(adsCount >= 1 && adsCount <= 5);

  /// Converts the options into a Map for transmission over the method channel.
  Map<String, dynamic> toMap() {
    return {'adId': adId, 'isTesting': isTesting, 'adsCount': adsCount};
  }
}
