/// Represents a single image in a Native Ad with its associated metadata.
class FlutterNativeAdImage {
  /// The URL string for the image.
  final String? url;

  /// The width of the image in pixels (if available).
  final double? width;

  /// The height of the image in pixels (if available).
  final double? height;

  /// The scale of the image (if available).
  final double? scale;

  FlutterNativeAdImage({this.url, this.width, this.height, this.scale});

  /// Creates a [FlutterNativeAdImage] from a [map].
  factory FlutterNativeAdImage.fromMap(Map<String, dynamic> map) {
    return FlutterNativeAdImage(
      url: map['url'] as String?,
      width: (map['width'] as num?)?.toDouble(),
      height: (map['height'] as num?)?.toDouble(),
      scale: (map['scale'] as num?)?.toDouble(),
    );
  }

  /// Backward-compatible way to get the URL if you treat this as a string.
  @override
  String toString() => url ?? "";
}

/// Represents a loaded Native Ad from AdMob with all available metadata.
class FlutterNativeAd {
  /// Unique identifier generated by the plugin for this specific ad instance.
  final String id;

  /// The headline of the ad (e.g., "Install App").
  final String? headline;

  /// The main descriptive text of the ad.
  final String? body;

  /// The name of the advertiser (e.g., "Google" or the app developer name).
  final String? advertiser;

  /// Metadata for the square icon image.
  final FlutterNativeAdImage? icon;

  /// A list of images associated with the ad.
  final List<FlutterNativeAdImage> images;

  /// Backward-compatible getter that returns the URL of the first image.
  String? get cover => images.isNotEmpty ? images.first.url : null;

  /// The text for the call-to-action button (e.g., "Install", "Open", "Learn More").
  final String? cta;

  /// The star rating of the advertised product (0.0 to 5.0).
  final double? starRating;

  /// The store name where the app is available (e.g., "Google Play", "App Store").
  final String? store;

  /// The price of the advertised product (e.g., "Free" or "$0.99").
  final String? price;

  /// The URL for the "Why this ad?" (AdChoices) information page.
  final String? adChoicesUrl;

  /// The text to accompany the AdChoices icon (if provided by the SDK).
  final String? adChoicesText;

  /// The aspect ratio of the primary media content (width/height).
  final double? aspectRatio;

  FlutterNativeAd({
    required this.id,
    this.headline,
    this.body,
    this.advertiser,
    this.icon,
    this.images = const [],
    this.cta,
    this.starRating,
    this.store,
    this.price,
    this.adChoicesUrl,
    this.adChoicesText,
    this.aspectRatio,
  });

  /// Creates a [FlutterNativeAd] instance from a [map] received from the native platform.
  factory FlutterNativeAd.fromMap(Map<String, dynamic> map) {
    // Handle images as either a list of maps (new) or a comma-separated string (old)
    List<FlutterNativeAdImage> imagesList = [];
    final imagesData = map['images'];

    if (imagesData is List) {
      imagesList = imagesData
          .map((e) => FlutterNativeAdImage.fromMap(Map<String, dynamic>.from(e as Map)))
          .toList();
    } else if (imagesData is String && imagesData.isNotEmpty) {
      imagesList = imagesData.split(',').map((url) => FlutterNativeAdImage(url: url)).toList();
    }

    // Handle icon similarly
    FlutterNativeAdImage? icon;
    final iconData = map['icon'];
    if (iconData is Map) {
      icon = FlutterNativeAdImage.fromMap(Map<String, dynamic>.from(iconData));
    } else if (iconData is String) {
      icon = FlutterNativeAdImage(url: iconData);
    }

    return FlutterNativeAd(
      id: map['id'] as String,
      headline: map['headline'] as String?,
      body: map['body'] as String?,
      advertiser: map['advertiser'] as String?,
      icon: icon,
      images: imagesList,
      cta: map['cta'] as String?,
      starRating:
          (map['starRating'] as num?)?.toDouble() ?? double.tryParse(map['starRating'] as String? ?? ""),
      store: map['store'] as String?,
      price: map['price'] as String?,
      adChoicesUrl: map['adChoicesUrl'] as String?,
      adChoicesText: map['adChoicesText'] as String?,
      aspectRatio: (map['aspectRatio'] as num?)?.toDouble(),
    );
  }
}

/// Options for loading one or more native ads.
class FlutterNativeAdOptions {
  /// The AdMob ad unit ID to load.
  final String adId;

  /// Whether to use test ads instead of live ads.
  final bool isTesting;

  /// The number of ads to request from the server (min 1, max 5).
  final int adsCount;

  /// Creates a new [FlutterNativeAdOptions] instance.
  FlutterNativeAdOptions({required this.adId, this.isTesting = false, this.adsCount = 1})
    : assert(adsCount >= 1 && adsCount <= 5);

  /// Converts the options into a Map for transmission over the method channel.
  Map<String, dynamic> toMap() {
    return {'adId': adId, 'isTesting': isTesting, 'adsCount': adsCount};
  }
}

/// Represents an AdRequest with various targeting and configuration options.
class AdRequest {
  /// A list of keywords to be used for targeting.
  final List<String>? keywords;

  /// The content URL for the ad request.
  final String? contentUrl;

  /// A list of neighboring content URLs for the ad request.
  final List<String>? neighboringContentUrls;

  /// Whether non-personalized ads should be requested.
  final bool? nonPersonalizedAds;

  /// The HTTP timeout in milliseconds.
  final int? httpTimeoutMillis;

  /// An identifier for mediation extras.
  final String? mediationExtrasIdentifier;

  /// A map of extra parameters.
  final Map<String, String>? extras;

  /// A list of mediation extras.
  final List<MediationExtras>? mediationExtras;

  const AdRequest({
    this.keywords,
    this.contentUrl,
    this.neighboringContentUrls,
    this.nonPersonalizedAds,
    this.httpTimeoutMillis,
    this.mediationExtrasIdentifier,
    this.extras,
    this.mediationExtras,
  });

  /// Converts the AdRequest into a Map for transmission over the method channel.
  Map<String, dynamic> toMap() {
    return {
      'keywords': keywords,
      'contentUrl': contentUrl,
      'neighboringContentUrls': neighboringContentUrls,
      'nonPersonalizedAds': nonPersonalizedAds,
      'httpTimeoutMillis': httpTimeoutMillis,
      'mediationExtrasIdentifier': mediationExtrasIdentifier,
      'extras': extras,
      'mediationExtras': mediationExtras?.map((e) => e.toMap()).toList(),
    };
  }
}

/// Contains information for a particular ad network set by the developer.
abstract class MediationExtras {
  /// Fully-qualified name of an Android MediationExtras class.
  String getAndroidClassName();

  /// Name of an iOS class that conforms to the GADAdNetworkExtras protocol.
  String getIOSClassName();

  /// Key-Value pair to be sent to the host platform to parse.
  Map<String, dynamic> getExtras();

  /// Converts the extras into a Map for transmission over the method channel.
  Map<String, dynamic> toMap() {
    return {
      'androidClassName': getAndroidClassName(),
      'iosClassName': getIOSClassName(),
      'extras': getExtras(),
    };
  }
}

/// A generic implementation of [MediationExtras] to support any mediation provider.
class GenericMediationExtras extends MediationExtras {
  final String androidClassName;
  final String iosClassName;
  final Map<String, dynamic> extras;

  GenericMediationExtras({
    required this.androidClassName,
    required this.iosClassName,
    required this.extras,
  });

  @override
  String getAndroidClassName() => androidClassName;

  @override
  String getIOSClassName() => iosClassName;

  @override
  Map<String, dynamic> getExtras() => extras;
}
